# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfs < Formula
  desc "DittoFS server daemon — modular virtual filesystem with pluggable storage backends"
  homepage "https://github.com/marmos91/dittofs"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.0/dfs_0.6.0_Darwin_x86_64.tar.gz"
      sha256 "b14632457e227ca9efd564a8a05005a53e0511f088c5f0f723b24e50a50719d2"

      def install
        bin.install "dfs"
        generate_completions_from_executable(bin/"dfs", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.0/dfs_0.6.0_Darwin_arm64.tar.gz"
      sha256 "f70736b822a4f69e5fee23607ea87801933b3cc25fb35132397254fa3ce2aa6f"

      def install
        bin.install "dfs"
        generate_completions_from_executable(bin/"dfs", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.0/dfs_0.6.0_Linux_x86_64.tar.gz"
      sha256 "3e3510b5fc03c30f155c2879632468c9fa3df2fc0ee6a961acbdd72567c4fae6"
      def install
        bin.install "dfs"
        generate_completions_from_executable(bin/"dfs", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.0/dfs_0.6.0_Linux_arm64.tar.gz"
      sha256 "d7385d914b429998c91fd0fc13e0bb92ffcf1dbfd5ee66295ebf95a1c565e8e6"
      def install
        bin.install "dfs"
        generate_completions_from_executable(bin/"dfs", "completion")
      end
    end
  end

  test do
    system bin/"dfs", "version", "--short"
  end
end
