# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfsctl < Formula
  desc "DittoFS CLI client — remote management for DittoFS servers"
  homepage "https://github.com/marmos91/dittofs"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.1/dfsctl_0.6.1_Darwin_x86_64.tar.gz"
      sha256 "bafc7e9d3bd65a6d6d735142dc2daf723d3053d7781c45d76e52c59a0fa368d8"

      def install
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.1/dfsctl_0.6.1_Darwin_arm64.tar.gz"
      sha256 "bba809b6c21e19a5b7633ecf4a73e73a8c089f1e7ae37fb0398b0f4ed912adc7"

      def install
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.1/dfsctl_0.6.1_Linux_x86_64.tar.gz"
      sha256 "99261cb000955424cdefd17cd9bf960c6fc42e9b6bfffb816a46f8ba2093526c"
      def install
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.1/dfsctl_0.6.1_Linux_arm64.tar.gz"
      sha256 "fb8efc88c8785b196a1dd815ba8ac93647d90a8f9fc1801fb9bed25871de73db"
      def install
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
  end

  test do
    system bin/"dfsctl", "version", "--short"
  end
end
