# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfsctl < Formula
  desc "DittoFS CLI client — remote management for DittoFS servers"
  homepage "https://github.com/marmos91/dittofs"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.0/dfsctl_0.6.0_Darwin_x86_64.tar.gz"
      sha256 "24bb6ad269d9d9664601a88fd3529fa55e9d32c9f8d3de140230462ef24409b8"

      def install
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.0/dfsctl_0.6.0_Darwin_arm64.tar.gz"
      sha256 "23d67cc85a471cb65569e2b89ec724b3cd74da883c6f061da9dd112c45550c65"

      def install
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.0/dfsctl_0.6.0_Linux_x86_64.tar.gz"
      sha256 "4a7e7dab521e22a75b233dc9ae0bd87c54fee34df2abdda35398e6d61612b2a4"
      def install
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.6.0/dfsctl_0.6.0_Linux_arm64.tar.gz"
      sha256 "c7110c6162d5a1d00cf9084740b3f0dd9a65b32bd87386c2f26f026644c7a495"
      def install
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
  end

  test do
    system bin/"dfsctl", "version", "--short"
  end
end
