# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfs-pro" do
  version "0.22.0"

  on_macos do
    on_intel do
      sha256 "fcc9d154a9fb81102a722fa82fbf8b6f47a6df51b90a2433bfb08250ea9e7ef1"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4aa4d770b64c029ae5d3220ff3dc6199820463fa8cec9acebc37520f36a4b628"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bd90a8ad83677afa6901cfbf1260d192e42994e0f9ba89df39ca64438c060609"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b67688d2595d469257663cc28f169c0056106530e636c06edc970b0bd56a3b8d"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dfs-pro"
  desc "DittoFS Pro - Virtual filesystem management platform with web dashboard"
  homepage "https://github.com/marmos91/dittofs-pro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfs-pro"

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/dfs-pro"]
  end

  # No zap stanza required

  caveats <<~EOS
    DittoFS Pro is now installed.

    To start the server:
      dfs-pro

    Default port: 8080
    Dashboard URL: http://localhost:8080
  EOS
end
