# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfs-pro" do
  version "0.32.0"

  on_macos do
    on_intel do
      sha256 "d45ca404a5d6a276865c827465d9219dc4c53c53fdeb2df3861751a081d0101c"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e185e3852fb77c9a635182c03e90ec05f7b8d8f5cd1ce0e943a3d7aa8df6b926"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4a1213e275c5a6a84dd0e9e26a50e42e89a0a1196dfd5e5e75605429af90e321"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce59ec7cb4ef988a25ed795b165450577f49bbddf1c43b6a9ea898ad1c72c185"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dfs-pro"
  desc "DittoFS Pro - Virtual filesystem management platform with web dashboard"
  homepage "https://github.com/marmos91/dittofs-pro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfs-pro"

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/dfs-pro"]
  end

  # No zap stanza required

  caveats <<~EOS
    DittoFS Pro is now installed.

    To start the server:
      dfs-pro

    Default port: 8080
    Dashboard URL: http://localhost:8080
  EOS
end
