# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfs-pro" do
  version "0.20.1"

  on_macos do
    on_intel do
      sha256 "2ca6338688feac9bf73e29ccc2e4612f481881dabc1f755b8b9f0f98db66dc09"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff40328d0c2b951bf5983e97329114853aef8a42ee68b2329e4985add84794e2"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "405f57fcb05e3fd0ed41789fda82bcb254c151aecbed2d650338aec3e4d95369"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "61b4ff2084f1548a7a9d4696d191e880f115ca9abab7c74669b3f892d6cfb414"
      url "https://s3.cubbit.eu/dittofs-pro-binaries/v#{version}/dfs-pro_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dfs-pro"
  desc "DittoFS Pro - Virtual filesystem management platform with web dashboard"
  homepage "https://github.com/marmos91/dittofs-pro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfs-pro"

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/dfs-pro"]
  end

  # No zap stanza required

  caveats <<~EOS
    DittoFS Pro is now installed.

    To start the server:
      dfs-pro

    Default port: 8080
    Dashboard URL: http://localhost:8080
  EOS
end
