# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfs" do
  version "0.34.1"

  on_macos do
    on_intel do
      sha256 "bec3a31feea1489702d8687d9a5187b411514d8a12e1709cc7c95363a7d35257"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "dddceee540a58a3117e56395049604edbd92a2efc5af1e02ec5e2e93c0c79f75"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "df079f14b0c73862fe582d47610fc8f9e4db2d9990eb13263cd6d50fbd3c08cc"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "08accbb8136af1dffd7101297c20babada356ea3648c0a321ebb4ca881ac51fd"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "dfs"
  desc "DittoFS server daemon — modular virtual filesystem with pluggable storage backends"
  homepage "https://github.com/marmos91/dittofs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfs"

  # No zap stanza required

end
