# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfs" do
  version "0.29.1"

  on_macos do
    on_intel do
      sha256 "bd59d299507e594919084e6db5af8f9fb98074fad3700c1f0285d8fb7d505470"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "922f7d49988ed179d6cd85c561b35eb2d339ac4bea2656bcc73d0d445fd65f9c"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d855c3ac040705df8a3a5aff2e4396b79104caec0e9280026bf0c36a3707858d"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "11d6540a1ae6fb369bb2121b096c8d9d82f950f688dc9eee487d912c2614b6c1"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "dfs"
  desc "DittoFS server daemon — modular virtual filesystem with pluggable storage backends"
  homepage "https://github.com/marmos91/dittofs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfs"

  # No zap stanza required

end
