# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfs" do
  version "0.28.0"

  on_macos do
    on_intel do
      sha256 "b804cbf57ca9cea0b0b17aca0f7b0959235d870db81ff3b313381f087a3cc601"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ba1c3a33d02ae18ceb1bb69535242c9f7e13dd3642bb5e62a35538a2cfc6dce9"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "502e6da62c433efbb8475f3c41533e12a537971c877f58685f2c13160f39f36d"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "70570e50acfbd5bb1bf64189cc532910965e1e5a9b399a7dbaf8f89bca4ff933"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfs_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "dfs"
  desc "DittoFS server daemon — modular virtual filesystem with pluggable storage backends"
  homepage "https://github.com/marmos91/dittofs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfs"

  # No zap stanza required

end
