# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfsctl" do
  version "0.33.0"

  on_macos do
    on_intel do
      sha256 "d117ca72ac5ff82d4e1d039d05b90a246ca0f2e331cf4f9d40e883f6f63ff700"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "945c904d237c055c52144deacce0fba026dd487a96952dcf90283bad93e0ec39"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "35e88119fe6b08787fda31d9627d11844a4d1daad80f53d66e6f5228b486e88b"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ccc1ca7320489d1ca68bebe53d0a8876e36f6c4c1f15097b24c5fa3131392a61"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "dfsctl"
  desc "DittoFS CLI client — remote management for DittoFS servers"
  homepage "https://github.com/marmos91/dittofs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfsctl"

  # No zap stanza required

end
