# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfsctl" do
  version "0.28.1"

  on_macos do
    on_intel do
      sha256 "c63de65817b6a66f8bb34f56f6fcc912e0ff0bc61eb8e3601100b2f5dff597aa"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8a16fe9a99d20318501575423eaa908a4a31702efa085b4ef0f9b9df6c9cc9c8"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb75ba29e8ca85fc1f3eb94400d22fa1ea74c415de4ee0ef4bc8567eee555f2f"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0e946d31cd124a41e6b96af1bba546f7b824e42caefd6f868779d884e4c6d8ab"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "dfsctl"
  desc "DittoFS CLI client — remote management for DittoFS servers"
  homepage "https://github.com/marmos91/dittofs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfsctl"

  # No zap stanza required

end
