# This file was generated by GoReleaser. DO NOT EDIT.
cask "dfsctl" do
  version "0.26.0"

  on_macos do
    on_intel do
      sha256 "c39a7a197bdd4ab22dbc5c7d992e18937124d3c174162c9cf6d01f0357fe7583"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "898760a8d0ef8ed0c45e0370a6e7ee92392df8dd377f689ec84a7ccadd94278a"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a7b51ba6906b4122cd3f8b9f234450e98921fc3593cb1f66b75cf6463f2d0494"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e62709343e89a1b195a1202bf5387165b281f292610cd6ee68e5b628d3afa688"
      url "https://github.com/marmos91/dittofs/releases/download/v#{version}/dfsctl_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "dfsctl"
  desc "DittoFS CLI client — remote management for DittoFS servers"
  homepage "https://github.com/marmos91/dittofs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dfsctl"

  # No zap stanza required

end
