# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfs < Formula
  desc "DittoFS server daemon — modular virtual filesystem with pluggable storage backends"
  homepage "https://github.com/marmos91/dittofs"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marmos91/dittofs/releases/download/v0.7.0/dfs_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "d5d541e46d602f62a6ade9a98ce48baabc65e84ac8fe4bc59ede7ba3a31375ba"

      define_method(:install) do
        bin.install "dfs"
        generate_completions_from_executable(bin/"dfs", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marmos91/dittofs/releases/download/v0.7.0/dfs_0.7.0_Darwin_arm64.tar.gz"
      sha256 "2f91109b1156391381fc0ed13ed0f3c7511623000a0a157eb7fc1aa0e1968140"

      define_method(:install) do
        bin.install "dfs"
        generate_completions_from_executable(bin/"dfs", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.7.0/dfs_0.7.0_Linux_x86_64.tar.gz"
      sha256 "3d4a499246d4a3e96bdc1ef186706b1deb9e4c0726db812aeb99d53daccdda39"
      define_method(:install) do
        bin.install "dfs"
        generate_completions_from_executable(bin/"dfs", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.7.0/dfs_0.7.0_Linux_arm64.tar.gz"
      sha256 "de112cb18c1adfa80c5e761f501813f986b4efe7530af7f2afa6bc42a6fe6461"
      define_method(:install) do
        bin.install "dfs"
        generate_completions_from_executable(bin/"dfs", "completion")
      end
    end
  end

  test do
    system bin/"dfs", "version", "--short"
  end
end
