# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfsctl < Formula
  desc "DittoFS CLI client — remote management for DittoFS servers"
  homepage "https://github.com/marmos91/dittofs"
  version "0.8.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marmos91/dittofs/releases/download/v0.8.3/dfsctl_0.8.3_Darwin_x86_64.tar.gz"
      sha256 "a46c4b6946c85e9b2a5130254661c2b4fcf5fe538d48ced79b3f77f6b63d91a0"

      define_method(:install) do
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marmos91/dittofs/releases/download/v0.8.3/dfsctl_0.8.3_Darwin_arm64.tar.gz"
      sha256 "0b9ea6bf48fe94fdff91ede39bb98815d83411fc157e3bb08417411c8fd6a313"

      define_method(:install) do
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.8.3/dfsctl_0.8.3_Linux_x86_64.tar.gz"
      sha256 "d3241885cbe122310517636973541b2c28d579fc9baf1fdacb6cd768d9a39387"
      define_method(:install) do
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.8.3/dfsctl_0.8.3_Linux_arm64.tar.gz"
      sha256 "ce44d9465ad9a2444f646e010c9cbb954fc5569ade0eda641b2550b1dd91bb4b"
      define_method(:install) do
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
  end

  test do
    system bin/"dfsctl", "version", "--short"
  end
end
