# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfsctl < Formula
  desc "DittoFS CLI client — remote management for DittoFS servers"
  homepage "https://github.com/marmos91/dittofs"
  version "0.9.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marmos91/dittofs/releases/download/v0.9.6/dfsctl_0.9.6_Darwin_x86_64.tar.gz"
      sha256 "8b3554ac2130699c1ea43d9815ef02244fa7a4ff4ccff0978e44e5aea6140176"

      define_method(:install) do
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marmos91/dittofs/releases/download/v0.9.6/dfsctl_0.9.6_Darwin_arm64.tar.gz"
      sha256 "f9ed0c76efce2e60e7935c1e86a30d3cfcfa5e0201431321902ad67b90895718"

      define_method(:install) do
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.9.6/dfsctl_0.9.6_Linux_x86_64.tar.gz"
      sha256 "dc3d2dc6e0637276bd24c135ba9c403eafd02bcb9fbf173ec5c680b8851375f3"
      define_method(:install) do
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marmos91/dittofs/releases/download/v0.9.6/dfsctl_0.9.6_Linux_arm64.tar.gz"
      sha256 "6bd5f18a95df63a0b15a026ee2b5bbd9ea006bee7106594123ab9ce3f7c53282"
      define_method(:install) do
        bin.install "dfsctl"
        generate_completions_from_executable(bin/"dfsctl", "completion")
      end
    end
  end

  test do
    system bin/"dfsctl", "version", "--short"
  end
end
